telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://b528abbbcc74.ngrok-free.app"
  bot-name: "created_by_ys_younotes_bot"
  bot-token: "7689684416:AAFxpuhZe2wiq1PRdfXQSD7g8j4eNZYBeoI"
  trainer-chat-id: "-4655663559"
server:
  port: "8087"